# This workflow doesn't support cache invalidation for unused dependencies at the moment

kind: pipeline
type: ssh
name: Build on M1

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
  - name: Update rust
    commands:
      - /usr/local/bin/rustup-update
  - name: Run tests
    environment:
      SRCENV:
        from_secret: srcenv
      CARGO_HOME:
        from_secret: cargohome
      CARGO_TARGET_DIR:
        from_secret: cargotarget
    commands:
      - source $SRCENV/.cargo/env
      - export RUSTUP_HOME=$SRCENV/.rustup
      - export CARGO_LOG=cargo::core::compiler::fingerprint=info
      - cargo build --verbose
    when:
      event:
        exclude:
          - tag
  - name: Build bundle
    environment:
      SRCENV:
        from_secret: srcenv
      CARGO_HOME:
        from_secret: cargohome
      CARGO_TARGET_DIR:
        from_secret: cargotarget
      TARGET: aarch64-apple-darwin
      VERSION: ${DRONE_TAG}
      ARTIFACT: aarch64-apple-darwin
      TOOLDIR:
        from_secret: tooldir
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - source $SRCENV/.cargo/env
      - export RUSTUP_HOME=$SRCENV/.rustup
    when:
      event:
        - tag
